### ISSUE TITLE
Provide a nice deploy to Python notebook in Watson Studio

### ISSUE THREAD

**Issue by dtoczala** [modlanglais/ibm-cloud-backup#3]
Need a way to deploy this into Watson Studio - AND have it auto-update as we make improvements.  Not sure if this is possible - we might need to update the code in our "master" Studio instance, and then publish back out to GitHub.....

**Comment by modcarroll** [comment]
Done: https://github.com/modlanglais/ibm-cloud-backup-notebook

**Comment by dtoczala** [comment]
My hero!!!
