### ISSUE TITLE
Watson Assistant Json Download vs your backup

### ISSUE THREAD

**Issue by PhilippeComte** [modlanglais/ibm-cloud-backup#9]
Hi , thanks for your work particularly for Discovery

Regarding Watson Assistant , what does your tool bring on top of the  Export / Import functions for skills available in Watson Assistant ? 
Do you allow for backuping several skills at the same time ? 
Thank you.

**Comment by modcarroll** [comment]
Hi Philippe, Yes this tool backs up all skills in the given instance(s) of Watson Assistant. So in the tool there is a space to put your service credentials, and if you have more than one instance of Watson Assistant that you would like to backup, you would put in an array of service credentials. Then, the tool will automatically get all of the skill IDs in those instances then download them all. It also gives customers an opportunity to manage their own backups if they so choose. Hope this helps!
